name: Build asterisk (cert)

on:
  workflow_dispatch:

  push:
    paths:
      - .github/workflows/build-cert-asterisk.yml
      - 'asterisk-certified-releases.txt'

jobs:
  build-cert-asterisk:
    timeout-minutes: 600
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        releases: ['11', '13', '16', '18']
      fail-fast: false

    steps:
      - run: |
          set -x
          echo "Processing asterisk (cert) releases for v. ${{ matrix.releases }}.x"


